### ISSUE TITLE
[UploadService] - 'n' sheets

### ISSUE THREAD

**Issue by Jhooomn** [raycu03/excelSrping#1]
![image](https://user-images.githubusercontent.com/32346414/71558957-ac88ed00-2a26-11ea-826d-ef13aa04472c.png)

- Porqué se indica específicamente la hoja #1 y no 'i' a medida que va iterando el ciclo?

**Comment by raycu03** [comment]
Porque aún no está terminando y ese uno está para probar. Debido a que retorno un valor en la función antes de terminar el for,  el ciclo no continúa, así que debo replantear esa parte.
